vich_uploader:
    db_driver: orm
    # Prise en charge de Php 8
    metadata:
        type: attribute

    mappings:
        home:
            uri_prefix: /images/home
            upload_destination: '%kernel.project_dir%/public/images/home'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        hotel:
            uri_prefix: /images/hotel
            upload_destination: '%kernel.project_dir%/public/images/hotel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image:
            uri_prefix: /images/image
            upload_destination: '%kernel.project_dir%/public/images/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        room:
            uri_prefix: /images/room
            upload_destination: '%kernel.project_dir%/public/images/room'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
